## Question(1) Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

### Answer :  3x3 NumPy array with random integers between 1 and 100

In [18]:
import numpy as np

In [24]:
import random

In [16]:
random.randrange(1,100)

54

In [34]:
np.random.rand(1,3,3)

array([[[0.06479916, 0.20817193, 0.62744185],
        [0.98086584, 0.56549205, 0.09726546],
        [0.33983026, 0.41856725, 0.84771493]]])

In [36]:
a = np.random.rand(1,3,3)

In [42]:
a.ndim

3

In [44]:
np.random.randint(1,100,size=(3,3))

array([[ 1, 92, 46],
       [95, 11, 72],
       [63, 63, 59]])

In [59]:
arr = np.random.randint(1,100,size=(3,3))

In [61]:
arr

array([[59, 21, 58],
       [14,  8, 93],
       [32, 86, 21]])

### Interchange its rows and columns

In [63]:
arr

array([[59, 21, 58],
       [14,  8, 93],
       [32, 86, 21]])

In [67]:
# Transpose of the array when interchange its rows to columns and columns to rows.
arr.T

array([[59, 14, 32],
       [21,  8, 86],
       [58, 93, 21]])

## Question(2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

### Answer : Generate a 1D NumPy array with 10 elements.

In [71]:
import numpy as np

In [73]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,55])

In [75]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 55])

In [77]:
arr1.ndim

1

#### Reshape arr1 into a 2x5 array.

In [85]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 55])

In [87]:
# Returns an array containing the same data with a new shape.

arr1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 55]])

#### Reshape arr1 into a 5x2 array.

In [93]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 55])

In [97]:
# Returns an array containing the same data with a new shape.
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 55]])

In [99]:
arr1.ndim

1

## Question (3) Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

### Answer : Create a 4x4 NumPy array with random float values

In [122]:
np.random.rand(4,4)

array([[0.61233918, 0.00275728, 0.92925369, 0.63609495],
       [0.0650356 , 0.41303198, 0.07991331, 0.24663442],
       [0.45540131, 0.80969873, 0.86170404, 0.23265038],
       [0.69329175, 0.28155558, 0.5029211 , 0.89158418]])

In [448]:
arr = np.random.rand(4,4)

#### Add a border of zeros around it, resulting in a 6x6 array.

In [450]:
arr

array([[0.21877333, 0.55763063, 0.47698926, 0.07857523],
       [0.23249264, 0.42290332, 0.9772761 , 0.49878104],
       [0.42609432, 0.76615053, 0.0542713 , 0.21018101],
       [0.4628962 , 0.77979147, 0.14489275, 0.62296157]])

In [464]:
#Number of values padded to the edges of each axis.

arr_with_border = np.pad(arr,pad_width=1,mode="constant",constant_values=0)

In [466]:
print(arr_with_border)

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.21877333 0.55763063 0.47698926 0.07857523 0.        ]
 [0.         0.23249264 0.42290332 0.9772761  0.49878104 0.        ]
 [0.         0.42609432 0.76615053 0.0542713  0.21018101 0.        ]
 [0.         0.4628962  0.77979147 0.14489275 0.62296157 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [ ]:
#The np.pad function is used to add a padding of width 1 around the array, and constant_values=0 specifies that the padding should consist of zeros. 
#The resulting array will be 6x6 with a border of zeros.

## Question (4) Using NumPy, create an array of integers from 10 to 60 with a step of 5.

### Answer : create an array of integers from 10 to 60 

In [5]:
import numpy as np
np.arange(10,60)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

#### Create an array of integers from 10 to 60 with a step of 5.

In [37]:
# Return evenly spaced values within a given interval.
# "arange" can be called with a varying number of positional arguments.

arr = np.arange(10,60)

In [39]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
arr[0:60:5]                   # [start:end:step]

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [35]:
np.arange(10,60,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [442]:
np.arange(10,61,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

## Question (5) Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

### Answer : NumPy array of strings ['python', 'numpy', 'pandas']

In [128]:
np.array(["python","numpy","pandas"])

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [131]:
a = np.array(["python","numpy","pandas"])

In [133]:
a

array(['python', 'numpy', 'pandas'], dtype='<U6')

### Different case transformations 
### Uppercase

In [135]:
# Return an array with the elements converted to uppercase.
np.char.upper(a)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

#### Lowercase

In [137]:
# Return an array with the elements converted to lowercase.
np.char.lower(a)

array(['python', 'numpy', 'pandas'], dtype='<U6')

#### Title case

In [151]:
# Return an array with the each elements first character converted to uppercase.
# In case use title or capitalize format.

np.char.title(a)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

#### Capitalized

In [148]:
# Return a copy of `a` with only the first character of each element capitalized.

np.char.capitalize(a)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

## Question (6) Generate a NumPy array of words. Insert a space between each character of every word in the array

### Answer :  Generate a NumPy array of words

In [413]:
arr = np.array(["Manisha","Annu","Santu"])

In [415]:
arr

array(['Manisha', 'Annu', 'Santu'], dtype='<U7')

#### Insert a space between each character of every word in the array¶

In [429]:
arr

array(['Manisha', 'Annu', 'Santu'], dtype='<U7')

In [425]:
spaced_words = np.array([' '.join(list(word)) for word in arr])

In [427]:
print(spaced_words)

['M a n i s h a' 'A n n u' 'S a n t u']


## Question (7) Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

### Answer : Create two 2D NumPy arrays 

In [178]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [180]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [182]:
arr1.ndim

2

In [184]:
arr2 = np.array([[4,7,9],[3,6,8],[1,2,5]])

In [186]:
arr2

array([[4, 7, 9],
       [3, 6, 8],
       [1, 2, 5]])

In [188]:
arr2.ndim

2

#### Perform element-wise 
#### Addition

In [193]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
arr2

array([[4, 7, 9],
       [3, 6, 8],
       [1, 2, 5]])

In [191]:
arr1 + arr2

array([[ 5,  9, 12],
       [ 7, 11, 14],
       [ 8, 10, 14]])

#### Subtraction

In [202]:
arr1 - arr2

array([[-3, -5, -6],
       [ 1, -1, -2],
       [ 6,  6,  4]])

#### Multiplication

In [204]:
arr1 * arr2

array([[ 4, 14, 27],
       [12, 30, 48],
       [ 7, 16, 45]])

#### Division

In [206]:
arr1 / arr2

array([[0.25      , 0.28571429, 0.33333333],
       [1.33333333, 0.83333333, 0.75      ],
       [7.        , 4.        , 1.8       ]])

## Question (8). Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

### Answer : Use NumPy to create a 5x5 identity matrix

#### Identity Matrix is a square matrix with a diagonal of ones and all other elements are Zero.

In [213]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [215]:
np.eye(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [401]:
identity_matrix = np.eye(5,dtype = int)

In [403]:
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### Extract its diagonal elements

In [405]:
diagonal_elements= np.diag(identity_matrix)

In [407]:
diagonal_elements

array([1, 1, 1, 1, 1])

In [409]:
identity_matrix,diagonal_elements

(array([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]]),
 array([1, 1, 1, 1, 1]))

## Question (9) Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

### Answer : Generate a NumPy array of 100 random integers between 0 and 1000

In [249]:
np.random.randint(0,1000,size = (10,10))

array([[779, 881,  26, 164, 444, 242, 815, 934, 749, 902],
       [109, 361, 939, 780, 962, 563,  56, 644,  61, 204],
       [452, 704, 827, 101, 707, 474, 544, 878, 562, 441],
       [862, 378, 594, 507,  80,  83, 861, 967, 920, 730],
       [541, 416, 620, 174, 769, 299, 419, 717, 975, 430],
       [ 97, 446, 422, 774, 348, 561, 133,   1,  19, 196],
       [871, 805, 880, 539, 912, 152, 227, 791,   2, 335],
       [381, 143, 387, 281, 737, 849, 507,  95,  58, 212],
       [711,  97, 447, 924, 437, 860, 589, 987,  72, 740],
       [414, 828, 660, 469, 858, 657,  71, 303, 561,  23]])

In [380]:
arr = np.random.randint(0,1000,size = (100))

In [382]:
arr

array([827,  22, 847, 244, 774, 265,  50, 615, 336, 948, 680, 745, 195,
       924, 305, 235, 739, 120, 762,  95, 121, 549,  16, 476, 598, 352,
       753, 469, 274, 679, 947, 869, 982,  12, 378, 352, 801, 533, 383,
        20, 878, 748, 850, 647, 916, 986, 485, 604, 697, 755, 963, 634,
       850, 261, 164, 763,  35,  95, 821, 225, 700, 334, 501, 433, 842,
       985, 977, 948, 999, 204,  57, 276, 180, 693, 157, 489, 863, 354,
       339, 837, 425, 785,  22, 378, 166, 554, 323, 819, 952, 418, 388,
       941, 575, 736, 525, 409, 844, 760,  25, 726])

#### Display all prime numbers in this array

In [364]:
arr.ndim

2

In [384]:
# Numpy has no built in function for finding prime number, so we can use additional libraries like :isprime() function of sympy library.
from sympy import isprime
# Find all prime numbers in this array

prime_numbers = [num for num in arr if isprime(num)]

In [386]:
arr,prime_numbers

(array([827,  22, 847, 244, 774, 265,  50, 615, 336, 948, 680, 745, 195,
        924, 305, 235, 739, 120, 762,  95, 121, 549,  16, 476, 598, 352,
        753, 469, 274, 679, 947, 869, 982,  12, 378, 352, 801, 533, 383,
         20, 878, 748, 850, 647, 916, 986, 485, 604, 697, 755, 963, 634,
        850, 261, 164, 763,  35,  95, 821, 225, 700, 334, 501, 433, 842,
        985, 977, 948, 999, 204,  57, 276, 180, 693, 157, 489, 863, 354,
        339, 837, 425, 785,  22, 378, 166, 554, 323, 819, 952, 418, 388,
        941, 575, 736, 525, 409, 844, 760,  25, 726]),
 [827, 739, 947, 383, 647, 821, 433, 977, 157, 863, 941, 409])

## Question(10) Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

### Answer : Create a NumPy array representing daily temperatures for a month

In [308]:
#Draw samples from a uniform distribution.
#Samples are uniformly distributed over the half-open interval[low, high] (includes low, but excludes high).
#Create a NumPy array representing daily temperatures for a month (30 days).
#Let Temperatures between 20 and 40 degrees

np.random.uniform(low = 20,high = 40,size = 30)                              

array([20.30131322, 26.98404982, 21.12411983, 28.66415051, 34.92178723,
       21.86340889, 31.01993431, 38.4928812 , 31.57859186, 29.53609609,
       21.57437333, 31.20043049, 35.73259246, 38.86428472, 25.00284387,
       31.38401372, 28.74311286, 20.25771344, 25.90799526, 31.09860374,
       27.66055151, 29.17909706, 25.14201056, 29.39880978, 30.04008689,
       28.87198979, 32.95829724, 23.84514177, 27.41312439, 22.19152693])

In [322]:
a = np.random.uniform(low = 20,high = 40,size = 30) 

In [324]:
a

array([35.52264322, 30.46471707, 21.54214735, 37.03314284, 38.27935402,
       32.61176562, 36.4083413 , 29.60657805, 38.4762195 , 34.84522712,
       25.39733728, 38.68351761, 20.60923229, 27.02463625, 35.4949011 ,
       35.40670972, 27.2316378 , 39.61290677, 35.20890689, 27.25227138,
       23.21081785, 32.53171847, 26.47434457, 21.25727072, 32.64375986,
       32.28066841, 36.04844643, 39.21489168, 37.96268999, 27.23571536])

In [330]:
# Calculate weekly averages (assuming a week is 7 days).

weekly_averages = [np.mean(a[i:i+7])   for i in range(0, len(a), 7)]

In [328]:
a,weekly_averages

(array([35.52264322, 30.46471707, 21.54214735, 37.03314284, 38.27935402,
        32.61176562, 36.4083413 , 29.60657805, 38.4762195 , 34.84522712,
        25.39733728, 38.68351761, 20.60923229, 27.02463625, 35.4949011 ,
        35.40670972, 27.2316378 , 39.61290677, 35.20890689, 27.25227138,
        23.21081785, 32.53171847, 26.47434457, 21.25727072, 32.64375986,
        32.28066841, 36.04844643, 39.21489168, 37.96268999, 27.23571536]),
 [33.123158774385885,
  30.663249728651326,
  31.916878787369743,
  31.493014305248543,
  32.59920267645584])